export interface TechnologyDef {
    name: string
    icon: string
    type: string
    color: string
}

export type technologyNames = keyof typeof technologies

const technologies: Record<string, TechnologyDef> = {
    prisma: {
        name: 'Prisma',
        icon: 'https://www.google.com/s2/favicons?domain=www.prisma.io&sz=256',
        type: 'database',
        color: '#2D3748',
    },
    react: {
        name: 'React',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/a/a7/React-icon.svg',
        type: 'frontend',
        color: '#61DAFB',
    },
    nextjs: {
        name: 'Next.js',
        icon: 'https://www.google.com/s2/favicons?domain=nextjs.org&sz=256',
        type: 'frontend',
        color: '#000000',
    },
    typescript: {
        name: 'TypeScript',
        icon: 'https://www.google.com/s2/favicons?domain=www.typescriptlang.org&sz=256',
        type: 'language',
        color: '#007ACC',
    },
    javascript: {
        name: 'JavaScript',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg',
        type: 'language',
        color: '#F7DF1E',
    },
    nodejs: {
        name: 'Node.js',
        icon: 'https://www.google.com/s2/favicons?domain=nodejs.org&sz=256',
        type: 'backend',
        color: '#8CC84B',
    },
    npm: {
        name: 'npm',
        icon: 'https://www.google.com/s2/favicons?domain=npmjs.com&sz=256',
        type: 'package manager',
        color: '#CB3837',
    },
    tailwindcss: {
        name: 'Tailwind CSS',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg',
        type: 'css framework',
        color: '#38B2AC',
    },
    express: {
        name: 'Express',
        icon: 'https://www.google.com/s2/favicons?domain=expressjs.com&sz=256',
        type: 'backend',
        color: '#000000',
    },
    mongodb: {
        name: 'MongoDB',
        icon: 'https://www.google.com/s2/favicons?domain=mongodb.com&sz=256',
        type: 'database',
        color: '#47A248',
    },
    graphql: {
        name: 'GraphQL',
        icon: 'https://www.google.com/s2/favicons?domain=graphql.org&sz=256',
        type: 'api',
        color: '#E10098',
    },
    docker: {
        name: 'Docker',
        icon: 'https://www.google.com/s2/favicons?domain=docker.com&sz=256',
        type: 'containerization',
        color: '#2496ED',
    },
    postgresql: {
        name: 'PostgreSQL',
        icon: 'https://www.google.com/s2/favicons?domain=postgresql.org&sz=256',
        type: 'database',
        color: '#336791',
    },
    redis: {
        name: 'Redis',
        icon: 'https://www.google.com/s2/favicons?domain=redis.io&sz=256',
        type: 'database',
        color: '#D82C20',
    },
    vuejs: {
        name: 'Vue.js',
        icon: 'https://www.google.com/s2/favicons?domain=vuejs.org&sz=256',
        type: 'frontend',
        color: '#42B883',
    },
    angular: {
        name: 'Angular',
        icon: 'https://www.google.com/s2/favicons?domain=angular.io&sz=256',
        type: 'frontend',
        color: '#DD0031',
    },
    flutter: {
        name: 'Flutter',
        icon: 'https://www.google.com/s2/favicons?domain=flutter.dev&sz=256',
        type: 'mobile',
        color: '#02569B',
    },
    kotlin: {
        name: 'Kotlin',
        icon: 'https://www.google.com/s2/favicons?domain=kotlinlang.org&sz=256',
        type: 'language',
        color: '#F18E33',
    },
    swift: {
        name: 'Swift',
        icon: 'https://www.google.com/s2/favicons?domain=swift.org&sz=256',
        type: 'language',
        color: '#F05138',
    },
    php: {
        name: 'PHP',
        icon: 'https://www.google.com/s2/favicons?domain=php.net&sz=256',
        type: 'language',
        color: '#777BB4',
    },
    ruby: {
        name: 'Ruby',
        icon: 'https://www.google.com/s2/favicons?domain=ruby-lang.org&sz=256',
        type: 'language',
        color: '#CC342D',
    },
    go: {
        name: 'Go',
        icon: 'https://www.google.com/s2/favicons?domain=golang.org&sz=256',
        type: 'language',
        color: '#00ADD8',
    },
    dart: {
        name: 'Dart',
        icon: 'https://www.google.com/s2/favicons?domain=dart.dev&sz=256',
        type: 'language',
        color: '#00BFFF',
    },
    rust: {
        name: 'Rust',
        icon: 'https://www.google.com/s2/favicons?domain=rust-lang.org&sz=256',
        type: 'language',
        color: '#000000',
    },
    powershell: {
        name: 'PowerShell',
        icon: 'https://www.google.com/s2/favicons?domain=www.powershellgallery.com&sz=256',
        type: 'scripting',
        color: '#5391FE',
    },
    bash: {
        name: 'Bash',
        icon: 'https://www.google.com/s2/favicons?domain=www.gnu.org&sz=256',
        type: 'scripting',
        color: '#4EAA25',
    },
    html: {
        name: 'HTML',
        icon: 'https://www.google.com/s2/favicons?domain=www.w3.org&sz=256',
        type: 'markup',
        color: '#E34F26',
    },
    css: {
        name: 'CSS',
        icon: 'https://www.google.com/s2/favicons?domain=www.w3.org&sz=256',
        type: 'css',
        color: '#1572B6',
    },
    mysql: {
        name: 'MySQL',
        icon: 'https://www.google.com/s2/favicons?domain=mysql.com&sz=256',
        type: 'database',
        color: '#4479A1',
    },
    sqlite: {
        name: 'SQLite',
        icon: 'https://www.google.com/s2/favicons?domain=www.sqlite.org&sz=256',
        type: 'database',
        color: '#003B57',
    },
    firebase: {
        name: 'Firebase',
        icon: 'https://www.google.com/s2/favicons?domain=firebase.google.com&sz=256',
        type: 'backend',
        color: '#FFCA28',
    },
    word: {
        name: 'Word',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Microsoft_Office_Word_%282019%E2%80%93present%29.svg/512px-Microsoft_Office_Word_%282019%E2%80%93present%29.svg.png?20210821050502',
        type: 'document',
        color: '#2B579A',
    },
    excel: {
        name: 'Excel',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/3/34/Microsoft_Office_Excel_%282019%E2%80%93present%29.svg',
        type: 'spreadsheet',
        color: '#217346',
    },
    powerpoint: {
        name: 'PowerPoint',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/0/0d/Microsoft_Office_PowerPoint_%282019%E2%80%93present%29.svg',
        type: 'presentation',
        color: '#C94D00',
    },
    microsoft: {
        name: 'Microsoft',
        icon: 'https://www.google.com/s2/favicons?domain=microsoft.com&sz=256',
        type: 'software',
        color: '#F25022',
    },
    office: {
        name: 'Office',
        icon: 'https://www.google.com/s2/favicons?domain=office.com&sz=256',
        type: 'software',
        color: '#a94dde',
    },
    windows: {
        name: 'Windows',
        icon: '/images/tech/windows.svg',
        type: 'operating system',
        color: '#0078D6',
    },
    linux: {
        name: 'Linux',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/35/Tux.svg/506px-Tux.svg.png?20220320193426',
        type: 'operating system',
        color: '#FCC624',
    },
    debian: {
        name: 'Debian',
        icon: 'https://www.google.com/s2/favicons?domain=debian.org&sz=256',
        type: 'operating system',
        color: '#A81D33',
    },
    ubuntu: {
        name: 'Ubuntu',
        icon: 'https://www.google.com/s2/favicons?domain=ubuntu.com&sz=256',
        type: 'operating system',
        color: '#E95420',
    },
    c: {
        name: 'C',
        icon: '/images/tech/c.svg',
        type: 'language',
        color: '#a4b4c7',
    },
    cplusplus: {
        name: 'C++',
        icon: 'https://www.google.com/s2/favicons?domain=www.iso.org&sz=256',
        type: 'language',
        color: '#00599C',
    },
    csharp: {
        name: 'C#',
        icon: 'https://www.google.com/s2/favicons?domain=www.iso.org&sz=256',
        type: 'language',
        color: '#239120',
    },
    java: {
        name: 'Java',
        icon: 'https://www.google.com/s2/favicons?domain=www.oracle.com&sz=256',
        type: 'language',
        color: '#007396',
    },
    dotnet: {
        name: '.NET',
        icon: 'https://www.google.com/s2/favicons?domain=dotnet.microsoft.com&sz=256',
        type: 'framework',
        color: '#512BD4',
    },
    git: {
        name: 'Git',
        icon: 'https://www.google.com/s2/favicons?domain=git-scm.com&sz=256',
        type: 'version control',
        color: '#F05032',
    },
    github: {
        name: 'GitHub',
        icon: 'https://www.google.com/s2/favicons?domain=github.com&sz=256',
        type: 'version control',
        color: '#181717',
    },
    gitlab: {
        name: 'GitLab',
        icon: 'https://www.google.com/s2/favicons?domain=gitlab.com&sz=256',
        type: 'version control',
        color: '#FC6D26',
    },
    i18n: {
        name: 'i18n',
        icon: '/images/tech/i18n.png',
        type: 'internationalization',
        color: '#7986cb',
    },
    eslint: {
        name: 'ESLint',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/ESLint_logo.svg/1200px-ESLint_logo.svg.png',
        type: 'linting',
        color: '#4B32C3',
    },
    prettier: {
        name: 'Prettier',
        icon: 'https://www.google.com/s2/favicons?domain=prettier.io&sz=256',
        type: 'formatting',
        color: '#F7B93E',
    },
    vercel: {
        name: 'Vercel',
        icon: 'https://www.google.com/s2/favicons?domain=vercel.com&sz=256',
        type: 'hosting',
        color: '#000000',
    },
    shadcnui: {
        name: 'Shadcn UI',
        icon: 'https://www.google.com/s2/favicons?domain=ui.shadcn.com&sz=256',
        type: 'ui library',
        color: '#000000',
    },
    turbopack: {
        name: 'Turbopack',
        icon: '/images/tech/turbopack.png',
        type: 'build tool',
        color: '#fe1e57',
    },
    stripe: {
        name: 'Stripe',
        icon: 'https://www.google.com/s2/favicons?domain=stripe.com&sz=256',
        type: 'payment',
        color: '#6772E5',
    },
    drizzle: {
        name: 'Drizzle ORM',
        icon: 'https://www.google.com/s2/favicons?domain=orm.drizzle.team&sz=256',
        type: 'database',
        color: '#bfef4d',
    },
    discord: {
        name: 'Discord',
        icon: 'https://www.google.com/s2/favicons?domain=discord.com&sz=256',
        type: 'communication',
        color: '#7289DA',
    },
    webpack: {
        name: 'Webpack',
        icon: 'https://www.google.com/s2/favicons?domain=webpack.js.org&sz=256',
        type: 'build tool',
        color: '#8CC84B',
    },
    wordpress: {
        name: 'WordPress',
        icon: 'https://www.google.com/s2/favicons?domain=wordpress.org&sz=256',
        type: 'cms',
        color: '#21759B',
    },
    python: {
        name: 'Python',
        icon: 'https://www.google.com/s2/favicons?domain=python.org&sz=256',
        type: 'language',
        color: '#3776AB',
    },
    raspberrypi: {
        name: 'Raspberry Pi',
        icon: 'https://upload.wikimedia.org/wikipedia/de/thumb/c/cb/Raspberry_Pi_Logo.svg/500px-Raspberry_Pi_Logo.svg.png?20120729132916',
        type: 'hardware',
        color: '#A22846',
    },
    powerbi: {
        name: 'Power BI',
        icon: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/New_Power_BI_Logo.svg/600px-New_Power_BI_Logo.svg.png?20210102182532',
        type: 'business intelligence',
        color: '#F2C94C',
    },
    figma: {
        name: 'Figma',
        icon: 'https://www.google.com/s2/favicons?domain=figma.com&sz=256',
        type: 'design',
        color: '#F24E1E',
    },
}

export default technologies